package com.sword.mbg.dao;

import com.sword.mbg.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 02 23:54:06 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 02 23:54:06 CST 2019
     */
    int insertSelective(User record);
}